### PR TITLE
350 pending submit reminder

### LINKED ISSUE #350: BORROWER_PENDING_SUBMIT_REMINDER messages are never sent
access-scheme sets status to ACCEPTED and expired_at to None for as long as that endpoint existed: https://github.com/open-contracting/credere-backend/commit/e8ad3bdc6bf968efea2d71110c9fd58e48797457

`get_applications_to_remind_submit` (now `pending_submission_reminder`) would check for a status of ACCEPTED and an expired_at in a range since 21c9e718191043bcdc8a5f6f2715e6ecc4a1fd1f

This condition seems impossible to match, unless I'm missing something.

So, no `send_mail_submit_reminder` emails are ever sent, if that's the case.

```
# SELECT * FROM message WHERE type = 'BORROWER_PENDING_SUBMIT_REMINDER';
(0 rows)
```

----

If this issue is closed, please update occurrences of :issue:\`350\` in the code with updated documentation.

### LINKED ISSUE #355: mail: Incorrect template or subject for send_mail_intro_reminder
In #167, this commit dad078253ea065627c0a6ef04a3971786902c9dc changed `send_mail_intro_reminder` to use the same template as `send_invitation_email`, whereas it used to use a different template (`INTRO_REMINDER_TEMPLATE_NAME` at the time, now should be `Access_to_credit_reminder`).

Edit: Ah, I see now that `Access_to_credit_reminder` is used for `send_mail_submit_reminder` (though, I think that email is never sent #350), so it probably won't work for `send_mail_intro_reminder` – assuming that's the correct pairing. I think it is weird to send an identical email as a reminder. There should be at least a different subject.

### PR DESCRIPTION
**Pull request by yolile**
closes #350 
closes #355

### CODE REVIEW

**Comment by jpmckinney** [comment]
Cool, I think we can merge `expiring_soon`'s code and docs into its caller, since it has only a single caller now.

**Comment by jpmckinney** [comment]
I noticed a bug. I'll fix it while fixing tests.

**Comment by yolile** [comment]
I'm still working on this, including setting up the tests and fixing the query logic as well

**Comment by jpmckinney** [comment]
Shouldn't send_mail_intro_reminder use Access_to_credit_reminder?

**Comment by jpmckinney** [comment]
Other than my last comment, please review my changes (I missed your update, so I ended up duplicating model changes, with a bit of a different approach, that makes it easier to compare the two methods).

**Comment by yolile** [comment]
My test is passing so I think all is good

**Review by jpmckinney — APPROVED** [review]

**Pull request merged**
