### PR TITLE
Refactor: statistics

### LINKED ISSUE #331: msme_approved_count is reinitialized in get_borrower_opt_in_stats()
It's assigned two different times, and then used once to construct the return value.

I assume the second one is the correct one, in which case we just delete the first one (and move the code for the second one into the return dict, to prevent this type of bug).

### LINKED ISSUE #334: Why do borrower sizes and genders need to strip " ?
From 13b0e80966a443327e60d9c8558ae889696b1c3b

I haven't tested without. Maybe it's not needed.

### LINKED ISSUE #335: Do "count distinct by size" statistics need to join awards?
I think it is a copy-paste error. 

* accepted_count_distinct_by_size
* submitted_count_distinct_by_size
* approved_count_distinct_by_size

Since there is a `distinct` call, I think the `join` ends up having no effect, since the join just adds non-distinct rows.

originated in 13b0e80966a443327e60d9c8558ae889696b1c3b and kept in https://github.com/open-contracting/credere-backend/commit/d6b543e2822370ffc30ab4fd3528e468fc5d43af#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR525

---

Same for these, which group by Application or Borrower id:

* accepted_count_unique https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR319
* approved_count https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR327

### LINKED ISSUE #336: Inconsistent ON clause for join(Award)
`.join(Award, Award.borrower_id == Borrower.id)` by

* accepted_count_unique 91f4ff7c009ad7fbc52ec1e61449160cba68e26d (irrelevant if #335 resolved)
* msme_accepted_count_woman (variable accepted_count_msme_woman_unique, renamed from accepted_count_woman_unique) d6b543e2822370ffc30ab4fd3528e468fc5d43af
* msme_submitted_count_woman  (variable submitted_count_msme_woman_unique) 91f4ff7c009ad7fbc52ec1e61449160cba68e26d

`.join(Award, Award.id == Application.award_id)` elsewhere.

Not sure if there is a reason, or if we should make it consistent with the rest.

I'm not sure why we have join clauses here. The tables will join with just the model name.

### LINKED ISSUE #337: proportion_of_submitted_out_of_opt_in uses borrower_submitted_at
The variable is named application_accepted_query, so borrower_accepted_at would have been expected
https://github.com/open-contracting/credere-backend/commit/10c95705b541101310b96ba4083594fe136f101e

Not sure if the variable name is incorrect, or the field.

For #333 I assume the variable name is incorrect.

### LINKED ISSUE #338: accepted_count_by_gender and sector_statistics use `Borrower.size != BorrowerSize.BIG` but this is not set if only accepted
https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d#diff-472af7cf72458a43f344b3f855c10ea1ce0c8fa285518a21d58686f7bb4fe80eR451

### LINKED ISSUE #339: msme_approved_count_woman is consistent with msme_approved_count, but not with msme_accepted_count_woman and msme_submitted_count_woman
Added in https://github.com/open-contracting/credere-backend/commit/91f4ff7c009ad7fbc52ec1e61449160cba68e26d

If I'm reading correctly, then msme_approved_count_woman and msme_approved_count_woman count the number of approved APPLICATIONS to MSME borrowers.

Whereas, msme_accepted_count_woman and msme_submitted_count_woman count the number of BORROWERS who are woman-owners of MSMEs, who accepted/submitted at least one application.

If this is clear in the frontend, then we can just add a comment to explain the difference in logic.

### PR DESCRIPTION
**Pull request by jpmckinney**
fixes #331 e41c54e
fixes #334 91063d8
fixes #335 c4239a0
fixes #336 3128206
fixes #337 e1f9ed8
fixes #338 437e8c3
fixes #339 1cc4542

Values changed in output:

* accepted_count_by_gender (gone in recent commit) and sector_statistics, due to #338
* msme_accepted_count_woman, msme_submitted_count_woman, due to #336

### CODE REVIEW

**Comment by yolile** [comment]
I think we should also change https://github.com/open-contracting/credere-backend/blob/main/app/routers/statistics.py to not check the database and calculate and return the statistics instead

**Comment by jpmckinney** [comment]
> I think we should also change https://github.com/open-contracting/credere-backend/blob/main/app/routers/statistics.py to not check the database and calculate and return the statistics instead
> 
> And then we could delete the update_statistics commands and Statistics table...

Sure, but let's do that in another PR, this one is a big changeset already.

**Comment by jpmckinney** [comment]
> delete the ... Statistics table

The table does keep a history of statistics for each day – not sure if this was a requirement.

**Comment by jpmckinney** [comment]
Okay to merge on my end.

**Pull request merged**
