### PR TITLE
feat: add lapse application endpoint

### PR DESCRIPTION
**Pull request by yolile**
ref #425, will be closed after implementing the changes in the front end

### CODE REVIEW

**Comment by jpmckinney** [comment]
Looks good, but I thought if status was SUBMITTED then lapsing should only be allowed if the lender uses external onboarding?

Can you update the flow diagram at https://credere.readthedocs.io/en/latest/contributing/index.html ? I think the DB diagram might also be out of date from earlier commits.

**Comment by yolile** [comment]
> Looks good, but I thought if status was SUBMITTED then lapsing should only be allowed if the lender uses external onboarding?

I can be allowed to work with any type of lender, but it will probably be STARTED for lenders without external onboarding. In any case, I can set it to STARTED for all cases (as the button will be on the last page of the application revision form anyway, and the application must be STARTED to get to that page)

> Can you update the flow diagram at https://credere.readthedocs.io/en/latest/contributing/index.html ? I think the DB diagram might also be out of date from earlier commits.

Sure

**Comment by yolile** [comment]
@jpmckinney ready for your review again

**Review by jpmckinney — APPROVED** [review]
Just for my understanding:

> lender lapses the application if the supplier is unresponsive during the review process

Does this mean the lender is contacting the supplier outside the "information requested" loop?

**Comment by yolile** [comment]
> Does this mean the lender is contacting the supplier outside the "information requested" loop?

Yes

**Pull request merged**
