### PR TITLE
366 exclude legal person

### LINKED ISSUE #366: More legal person exclusion rules
We are still creating some applications for natural person, when they set their organization type to "other" instead of "Persona natural colombiana" for example. The new rule to apply to mitigate this is:

tipo organizacion = persona natural OR regimen tributario = persona natural OR tipo doc empresa = Cédula

cc @sebasdocp

### PR DESCRIPTION
**Pull request by yolile**
closes #366

### CODE REVIEW

**Review by jpmckinney — APPROVED** [review]
I don't understand what the deleted code was trying to do (original https://github.com/open-contracting/credere-backend/commit/8c58d7a2d4929724c2a5ac813eeadc22fd900279)

**Comment by yolile** [comment]
> I don't understand what the deleted code was trying to do (original https://github.com/open-contracting/credere-backend/commit/8c58d7a2d4929724c2a5ac813eeadc22fd900279)

So, we have a feature to filter credit products by borrower type (e.g. some products are available for legal persons only and others for both or only natural persons). But currently, all our credit products are for legal persons only, so we are not sending invitations to natural persons at all (because otherwise they were accessing Credere but then not seeing any products at all, so until we have products for natural persons we don't need this filter). I will create an issue.

**Comment by jpmckinney** [comment]
Is the deleted code a problem? Will it not be relevant if we add products for natural persons?

**Comment by jpmckinney** [comment]
Ah, well the code hardcodes `SUPPLIER_TYPE_TO_EXCLUDE`, so might as well delete it and restore it with something better #372.

**Pull request merged**
