### PR TITLE
chore: Rename "background" to "commands" where relevant, to avoid confusion with FastAPI background tasks. Organize code accordingly.

### PR DESCRIPTION
**Pull request by jpmckinney**
Also:

* Rename _get_or_create_borrower to _create_or_update_borrower
* Add `_from_source` to functions that call `data_access`

### CODE REVIEW

**Comment by jpmckinney** [comment]
Sorry, ignore the request.

**Comment by yolile** [comment]
@jpmckinney do we need to update the cron jobs we have?

**Comment by jpmckinney** [comment]
I don't think so - they run `/usr/bin/docker compose --progress=quiet run --rm cron python -m app.commands <command>`, and I haven't renamed commands or moved the `app.commands` module.

**Comment by yolile** [comment]
Ah, the changes made to https://github.com/open-contracting/credere-backend/pull/261/files#diff-e6f90196d42bcd0142972be0372e95f81d2d010bf550d804b84f5dcf7f4f173f confused me, thanks!

**Comment by jpmckinney** [comment]
Ah, yeah, I deleted the sample crontab because that's purely deployment related, and we don't use those commands, exactly.

**Pull request merged**
